name: "Mutex"
description: "Blocks execution until parallel jobs completes"
inputs:
  server:
    description: "Mutex server host"
    required: true
  key:
    description: "Mutex key"
    required: true
runs:
  using: "docker"
  image: "action/Dockerfile"
  entrypoint: "main.sh"
  post-entrypoint: "clean.sh"
  args:
    - ${{ inputs.server }}/${{ inputs.key }}
branding:
  icon: volume-x  
  color: red